# This workflow will install Python dependencies, build sphinx docs, upload html as artifact.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: sphinx-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update and upgrade
      run: |
        sudo apt-get update
        sudo apt-get upgrade
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_docs.txt ]; then pip install -r requirements_docs.txt; fi
    - name: Install latex
      run: |
        sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - name: Build docs
      run: |
        cd docs
        make html
        make latex
        cd build/latex
        pdflatex project_name_example.tex
        # twice for updated references in the end
        pdflatex project_name_example.tex
        cd ../../..
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-pdf
        path: docs/build/latex/project_name_example.pdf


